"""
Export the WPA leaderboard to committed artifacts under results/ so it's visible
on GitHub (data/ and reports/ are git-ignored).

Writes results/wpa_leaderboard.md (top table) and results/wpa_leaderboard.csv (full).

Usage:
    python scripts/export_leaderboard.py
"""

import sys
from pathlib import Path

import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from cs2wpa.wpa import leaderboard  # noqa: E402

KILLS = Path("data/processed/wpa_kills.parquet")
OUT = Path("results")
TOP_N = 25
MIN_KILLS = 30


def main() -> None:
    if not KILLS.exists():
        sys.exit("No scored kills — run scripts/compute_wpa.py first.")
    kills = pl.read_parquet(KILLS)
    board = leaderboard(kills).filter(pl.col("kills") >= MIN_KILLS)
    n_maps = kills["demo"].n_unique()

    OUT.mkdir(exist_ok=True)
    board.with_columns(
        pl.col("total_wpa").round(3), pl.col("wpa_per_kill").round(4)
    ).write_csv(OUT / "wpa_leaderboard.csv")

    top = board.head(TOP_N)
    lines = [
        "# WPA Leaderboard — IEM Cologne Major 2026",
        "",
        f"Win Probability Added across **{n_maps} maps** / **{kills.height} kills**. "
        f"Players with ≥{MIN_KILLS} kills. WPA = sum of the win-probability swing each "
        "player's kills produced for their team — impact K/D can't see.",
        "",
        f"*Generated by `compute_wpa.py`; full table in [wpa_leaderboard.csv](wpa_leaderboard.csv).*",
        "",
        "| # | Player | Total WPA | Kills | WPA / kill |",
        "|---|--------|-----------|-------|------------|",
    ]
    for i, r in enumerate(top.iter_rows(named=True), 1):
        lines.append(f"| {i} | {r['attacker_name']} | {r['total_wpa']:.2f} | "
                     f"{r['kills']} | {r['wpa_per_kill']:.3f} |")
    (OUT / "wpa_leaderboard.md").write_text("\n".join(lines) + "\n")

    print(f"Wrote results/wpa_leaderboard.md (top {TOP_N}) and .csv ({board.height} players).")


if __name__ == "__main__":
    main()
